baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "My Magnolia Site"

# Always Capital M. All fixes are in Capital M theme.
theme = "Magnolia"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableMultilingual = false

# All below this line has been provided as suggested by GPT-5 and customized by myself.

# Enable draft content while developing

buildDrafts = true

# Site params used by the Magnolia theme
[params]
    subtitle = "Welcome to Sarah DeSantis's website"
# Any extra params the theme reads can go here.

enabled = true
callToAction = "Follow us:"

# Links is an array of tables below.

# If social media is desired, include something to this effect:
# [[params.socials.link]]
# name = "X"
# link = "https://x.com/yourhandle"
# [[params.socials.link]]
# name = "facebook"
# link = "https://facebook.com/yourpage"

# Menu definition (this builds .Site.Menus.main)
[[menu.main]]
    identifier = "home"
    name = "Home"
    URL = "/"
    weight = 1

[[menu.main]]
    identifier = "about"
    name = "About Me"
    URL = "/pages/about/"
    weight = 2

[[menu.main]]
    identifier = "work"
    name = "My Work"
    URL = "/pages/work/"
    weight = 3

[[menu.main]]
    identifier = "posts"
    name = "My Thoughts"
    URL = "/pages/posts/"
    weight = 4

[[menu.main]]
    identifier = "contact"
    name = "Contact Me"
    URL = "/pages/contact/"
    weight = 5

# Optional debug
disableKings = [] # keep default kinds