disabled = false
languageCode = 'en-US'
languageName = 'English'
title = 'Sarah DeSantis' # This will go in the Header as well
contentDir = "content/en"


# Change single params to "false" to remove from rendering
[params]
  subtitle = "A space for my thoughts" # This goes in the header and in the site title
  # PAGES
  [params.homepage]
    # Notice that SEO meta tags (what appears in google search results) can be set
    # in individual pages frontmatters `/content/<page>`
    ###
   # preTitle = 'Writer/Reader/Gardener'
    title = "Sarah DeSantis"
    # You can use some markdown safely here as long as you don't include line breaks
    intro= """
___

I’m Sarah, a writer, government executive, and idealist.

I’ve dedicated my career to improving the experience of being alive. As a journalist, I sought to share the knowledge needed for my readers to make the best choices for their communities. Currently, my work for the Commonwealth of Pennsylvania has allowed me to directly resolve issues and promote positive change for the benefit of all types of people.

You can also find me in my garden, volunteering with the Master Gardener program, assembling a jigsaw puzzle, attempting to finish house projects, and tidying my neighborhood as a board member of Keep Pennsylvania Beautiful.

        """
    mainButton = "About Me"
    mainButtonRef = "about" # Just write the name or slug of the page here
    secondButton = "Contact Me"
    secondButtonRef = "contacts" # Just write the name or slug of the page here
  # For the blog feed section (visible only if posts are rendered)
    blogTitle = "Stories by Me"
    blogButton= "More Stories"

[params.about]
  title = "About Me"
  description = "My drive to improve the experience of living for the people around me has taken me on a winding career path. I love to learn and be challenged. Above all, I value communication. Whether I’m writing a speech for a political figure, drafting an article, creating a newsletter, or leading a team, I prioritize clarity and openness. "
  layout = "about"
  image = "about/about.png"

[params.contacts]
  title = "Get in touch!"
  formCallToAction = "Want to collaborate? I have experience in a variety of areas and would love to hear about your projects. Please send me a note using the form below, and I’ll be in touch soon!"
  socialCallToAction = "You can add your own social media links below!" # These are the same as in [params.social]
  [params.contacts.form]
    formspreeLink = "https://yourformspreelink.com" #subscribe to formspree and add the link for the form here
    firstname = "First Name*"
    lastname = "Last Name*"
    email = "E-mail*"
    phone = "Phone Number*"
    Inquiry = "Write your message here.*"
    checkbox = "By checking this box, I acknowledge that this box is checked.*"
    submitBtn = "Submit"

[params.socials]
  enabled = false # enables/disables the whole social section in the footer
  callToAction= "Get connected with us on social networks >"
      [[params.socials.link]]
        name = "github"
        link = "https://github.com/ololiuhqui/magnolia-free-hugo-theme"
      [[params.socials.link]]
        name = "linkedin"
        link = ""
      [[params.socials.link]]
        name = "whatsapp"
        link = ""
      # You can add other socials here by copypasting the above section and
      # selecting the right name for the icon from here https://icons.getbootstrap.com/

[params.notfound]
  title = "Hey, it looks like you made it to a page that does not actually exist. This may be due to a mistyping of the URL, but most liklely it's a bug that needs fixed. Sorry!"

[params.single] # for posts pages (visible only if posts are rendered)
  similarContent= "Similar Content"
  toc= "Table of Contents"

[menus]
# PageRef should refer to the "translationKey" in `/content/<page>` frontmatter, names can be changed freely
  [[menus.main]]
  name = "Home"
  pageRef = "/"
  weight = 1
  [[menus.main]]
  name = "About Me"
  pageRef = "/about"
  weight = 2
  [[menus.main]]
  name = "My Work"
  pageRef = "/work"
  weight = 3
  [[menus.main]]
  name = "Contact Me"
  pageRef = "pages/contacts"
  weight = 4
