baseURL = "http://www.sarahdesantis.com"
languageCode = "en-us"
title = "Sarah DeSantis's Thoughts"

theme = "Magnolia"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableMultilingual = false
